-- The Cozzy Cup Cafe audit logs for inventory and revenue activity.
-- Tracks INSERT / UPDATE / DELETE on operational tables used by Inventory, Queue, and Revenue.

CREATE TABLE IF NOT EXISTS public.audit_logs (
  log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_id uuid,
  actor_email text,
  action text NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
  schema_name text NOT NULL DEFAULT 'public',
  table_name text NOT NULL,
  record_pk jsonb NOT NULL DEFAULT '{}'::jsonb,
  summary text,
  old_data jsonb,
  new_data jsonb
);

CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx
  ON public.audit_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_table_action_idx
  ON public.audit_logs (table_name, action, created_at DESC);

CREATE OR REPLACE FUNCTION public.audit_log_record_pk(p_table_name text, p_row jsonb)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_table_name
    WHEN 'inventory' THEN jsonb_build_object('ingredient_id', p_row -> 'ingredient_id')
    WHEN 'menu' THEN jsonb_build_object('item_id', p_row -> 'item_id')
    WHEN 'menu_ingredients' THEN jsonb_build_object('menu_ingredient_id', p_row -> 'menu_ingredient_id')
    WHEN 'inventory_transactions' THEN jsonb_build_object('transaction_id', p_row -> 'transaction_id')
    WHEN 'expenses' THEN jsonb_build_object('expense_id', p_row -> 'expense_id')
    WHEN 'orders' THEN jsonb_build_object('order_id', p_row -> 'order_id')
    WHEN 'order_items' THEN jsonb_build_object('order_item_id', p_row -> 'order_item_id')
    WHEN 'payments' THEN jsonb_build_object('payment_id', p_row -> 'payment_id')
    ELSE '{}'::jsonb
  END;
$$;

CREATE OR REPLACE FUNCTION public.audit_log_summary(
  p_action text,
  p_table_name text,
  p_old jsonb,
  p_new jsonb
)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_row jsonb := coalesce(p_new, p_old, '{}'::jsonb);
  v_name text;
BEGIN
  v_name := coalesce(
    v_row ->> 'name',
    v_row ->> 'expense_name',
    v_row ->> 'transaction_type',
    v_row ->> 'status',
    p_table_name
  );

  RETURN initcap(lower(p_action)) || ' on ' || p_table_name || ': ' || v_name;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_log_table_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old jsonb := NULL;
  v_new jsonb := NULL;
  v_row jsonb;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_new := to_jsonb(NEW);
    v_row := v_new;
  ELSIF TG_OP = 'UPDATE' THEN
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    v_row := v_new;
  ELSE
    v_old := to_jsonb(OLD);
    v_row := v_old;
  END IF;

  INSERT INTO public.audit_logs (
    actor_id,
    actor_email,
    action,
    schema_name,
    table_name,
    record_pk,
    summary,
    old_data,
    new_data
  )
  VALUES (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', 'system'),
    TG_OP,
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    public.audit_log_record_pk(TG_TABLE_NAME, v_row),
    public.audit_log_summary(TG_OP, TG_TABLE_NAME, v_old, v_new),
    v_old,
    v_new
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DO $$
DECLARE
  v_table text;
BEGIN
  FOREACH v_table IN ARRAY ARRAY[
    'inventory',
    'menu',
    'menu_ingredients',
    'inventory_transactions',
    'expenses',
    'orders',
    'order_items',
    'payments'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_%I_changes ON public.%I', v_table, v_table);
    EXECUTE format(
      'CREATE TRIGGER audit_%I_changes AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.audit_log_table_change()',
      v_table,
      v_table
    );
  END LOOP;
END $$;

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_logs_select_admin_only" ON public.audit_logs;
CREATE POLICY "audit_logs_select_admin_only"
ON public.audit_logs
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "audit_logs_service_manage" ON public.audit_logs;
CREATE POLICY "audit_logs_service_manage"
ON public.audit_logs
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

REVOKE ALL ON public.audit_logs FROM PUBLIC;
GRANT SELECT ON public.audit_logs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.audit_logs_log_id_seq TO authenticated;
