-- The Cozzy Cup Cafe one-copy repair SQL.
-- Run this whole file once in Supabase SQL Editor after the base schema exists.
--
-- This is intentionally an upgrade/repair script, not a drop-and-recreate schema:
-- - Keeps existing rows.
-- - Makes reports snapshot-safe.
-- - Makes received orders the real completed sales.
-- - Restores inventory when received orders are voided.
-- - Keeps old RPC names as compatibility wrappers for the current website.

-- ============================================================================
-- 1) Schema hardening
-- ============================================================================

ALTER TABLE public.inventory
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS classification text;

ALTER TABLE public.order_items
  ADD COLUMN IF NOT EXISTS item_name_snapshot text,
  ADD COLUMN IF NOT EXISTS size_label_snapshot text,
  ADD COLUMN IF NOT EXISTS category_snapshot text;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS voided_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS void_reason text;

CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('admin', 'staff', 'customer')),
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.menu_ingredients (
  menu_ingredient_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id bigint NOT NULL REFERENCES public.menu(item_id) ON DELETE CASCADE,
  ingredient_id bigint NOT NULL REFERENCES public.inventory(ingredient_id),
  quantity_required double precision NOT NULL CHECK (quantity_required > 0),
  unit_of_measure text NOT NULL DEFAULT 'unit',
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.menu_ingredients
  ADD COLUMN IF NOT EXISTS unit_of_measure text NOT NULL DEFAULT 'unit',
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.payments (
  payment_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(order_id),
  amount double precision NOT NULL DEFAULT 0 CHECK (amount >= 0),
  payment_method text NOT NULL DEFAULT 'cash',
  reference_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS amount double precision NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payment_method text NOT NULL DEFAULT 'cash',
  ADD COLUMN IF NOT EXISTS reference_number text,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();

UPDATE public.orders
SET status = 'pending'
WHERE status IS NULL
  OR trim(status) = ''
  OR status NOT IN ('pending', 'received', 'voided');

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_status_check;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_status_check CHECK (status IN ('pending', 'received', 'voided'));

UPDATE public.order_items oi
SET
  item_name_snapshot = coalesce(oi.item_name_snapshot, m.name),
  size_label_snapshot = coalesce(oi.size_label_snapshot, m.size_label),
  category_snapshot = coalesce(oi.category_snapshot, m.category)
FROM public.menu m
WHERE m.item_id = oi.menu_item_id
  AND (
    oi.item_name_snapshot IS NULL
    OR oi.size_label_snapshot IS NULL
    OR oi.category_snapshot IS NULL
  );

CREATE INDEX IF NOT EXISTS orders_status_created_at_idx
  ON public.orders (status, created_at);

CREATE INDEX IF NOT EXISTS order_items_order_id_idx
  ON public.order_items (order_id);

CREATE INDEX IF NOT EXISTS order_items_menu_item_id_idx
  ON public.order_items (menu_item_id);

CREATE INDEX IF NOT EXISTS inventory_transactions_reference_type_idx
  ON public.inventory_transactions (reference_id, transaction_type);

-- ============================================================================
-- 2) Admin helper
-- ============================================================================

CREATE OR REPLACE FUNCTION public.is_admin_app_user()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles ur
    WHERE ur.user_id = auth.uid()
      AND ur.role = 'admin'
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin_app_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin_app_user() TO authenticated;

-- ============================================================================
-- 3) Confirm order: create a pending order only
--    No payment and no inventory deduction happen here.
--    The sale is completed by mark_order_received().
-- ============================================================================

CREATE OR REPLACE FUNCTION public.confirm_pos_order(
  p_cashier_id bigint,
  p_client_id bigint,
  p_guest_display_name text,
  p_lines jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order_id bigint;
  v_total double precision := 0;
  rec_stock record;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'confirm_pos_order: not authorized (admin role required)';
  END IF;

  IF p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'confirm_pos_order: p_lines must be a non-empty JSON array';
  END IF;

  IF p_cashier_id IS NULL THEN
    RAISE EXCEPTION 'confirm_pos_order: p_cashier_id is required';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.cashier c WHERE c.cashier_id = p_cashier_id) THEN
    RAISE EXCEPTION 'confirm_pos_order: cashier_id % not found', p_cashier_id;
  END IF;

  IF p_client_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.clients cl WHERE cl.client_id = p_client_id) THEN
    RAISE EXCEPTION 'confirm_pos_order: client_id % not found', p_client_id;
  END IF;

  DROP TABLE IF EXISTS tmp_order_lines;
  DROP TABLE IF EXISTS tmp_menu_lines;
  DROP TABLE IF EXISTS tmp_ingredient_needs;

  CREATE TEMP TABLE tmp_order_lines ON COMMIT DROP AS
  WITH raw AS (
    SELECT
      (elem->>'menu_item_id')::bigint AS menu_item_id,
      (elem->>'quantity')::int AS quantity
    FROM jsonb_array_elements(p_lines) AS t(elem)
  ),
  cleaned AS (
    SELECT menu_item_id, quantity
    FROM raw
    WHERE menu_item_id IS NOT NULL AND quantity IS NOT NULL
  )
  SELECT menu_item_id, SUM(quantity)::int AS quantity
  FROM cleaned
  GROUP BY menu_item_id;

  IF NOT EXISTS (SELECT 1 FROM tmp_order_lines) THEN
    RAISE EXCEPTION 'confirm_pos_order: p_lines must include at least one valid menu item';
  END IF;

  IF EXISTS (SELECT 1 FROM tmp_order_lines WHERE quantity <= 0) THEN
    RAISE EXCEPTION 'confirm_pos_order: each quantity must be a positive integer';
  END IF;

  CREATE TEMP TABLE tmp_menu_lines ON COMMIT DROP AS
  SELECT
    t.menu_item_id,
    t.quantity,
    m.name,
    m.size_label,
    m.category,
    m.price,
    m.availability_status
  FROM tmp_order_lines t
  JOIN public.menu m ON m.item_id = t.menu_item_id;

  IF (SELECT count(*) FROM tmp_menu_lines) <> (SELECT count(*) FROM tmp_order_lines) THEN
    RAISE EXCEPTION 'confirm_pos_order: unknown menu_item_id in cart';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM tmp_menu_lines ml
    WHERE lower(coalesce(ml.availability_status, '')) <> 'available'
  ) THEN
    RAISE EXCEPTION 'confirm_pos_order: one or more menu items are unavailable';
  END IF;

  CREATE TEMP TABLE tmp_ingredient_needs ON COMMIT DROP AS
  SELECT
    mi.ingredient_id,
    SUM(ml.quantity * mi.quantity_required)::double precision AS required_quantity,
    string_agg(ml.name || ' x' || ml.quantity, ', ' ORDER BY ml.name) AS menu_summary
  FROM tmp_menu_lines ml
  JOIN public.menu_ingredients mi ON mi.menu_item_id = ml.menu_item_id
  GROUP BY mi.ingredient_id;

  IF EXISTS (
    SELECT 1
    FROM tmp_ingredient_needs n
    JOIN public.inventory i ON i.ingredient_id = n.ingredient_id
    WHERE i.is_active = false
  ) THEN
    RAISE EXCEPTION 'ARCHIVED_INGREDIENT: one or more menu recipes use archived ingredients';
  END IF;

  FOR rec_stock IN
    SELECT
      i.ingredient_id,
      i.name,
      i.current_quantity,
      n.required_quantity,
      n.menu_summary
    FROM tmp_ingredient_needs n
    JOIN public.inventory i ON i.ingredient_id = n.ingredient_id
    WHERE i.is_active = true
    ORDER BY i.ingredient_id
    FOR UPDATE OF i
  LOOP
    IF rec_stock.current_quantity < rec_stock.required_quantity THEN
      RAISE EXCEPTION 'INSUFFICIENT_STOCK: % required %, available %. Menu: %.',
        rec_stock.name,
        rec_stock.required_quantity,
        floor(rec_stock.current_quantity),
        rec_stock.menu_summary;
    END IF;
  END LOOP;

  SELECT SUM(price * quantity)::double precision
  INTO v_total
  FROM tmp_menu_lines;

  INSERT INTO public.orders (cashier_id, client_id, total_amount, status, guest_display_name)
  VALUES (
    p_cashier_id,
    p_client_id,
    v_total,
    'pending',
    NULLIF(trim(coalesce(p_guest_display_name, '')), '')
  )
  RETURNING order_id INTO v_order_id;

  INSERT INTO public.order_items (
    order_id,
    menu_item_id,
    quantity,
    unit_price,
    sub_total,
    item_name_snapshot,
    size_label_snapshot,
    category_snapshot
  )
  SELECT
    v_order_id,
    menu_item_id,
    quantity,
    price,
    price * quantity,
    name,
    size_label,
    category
  FROM tmp_menu_lines;

  RETURN v_order_id;
END;
$$;

REVOKE ALL ON FUNCTION public.confirm_pos_order(bigint, bigint, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.confirm_pos_order(bigint, bigint, text, jsonb) TO authenticated;

-- ============================================================================
-- 4) Mark received: this is the completed sale
--    Deducts stock, writes sale transactions, and creates one cash payment.
--    Compatibility: if an older pending order already has sale transactions or
--    payment rows, it will not double-deduct or double-pay.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.mark_order_received(p_order_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.orders%ROWTYPE;
  v_has_sale_transactions boolean := false;
  v_has_payment boolean := false;
  rec_stock record;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'mark_order_received: not authorized (admin role required)';
  END IF;

  SELECT *
  INTO v_order
  FROM public.orders
  WHERE order_id = p_order_id
    AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'mark_order_received: order % not found or not pending', p_order_id;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public.inventory_transactions it
    WHERE it.reference_id = p_order_id
      AND it.transaction_type = 'sale'
      AND it.quantity_change < 0
  )
  INTO v_has_sale_transactions;

  SELECT EXISTS (
    SELECT 1
    FROM public.payments p
    WHERE p.order_id = p_order_id
  )
  INTO v_has_payment;

  DROP TABLE IF EXISTS tmp_receive_ingredient_needs;

  CREATE TEMP TABLE tmp_receive_ingredient_needs ON COMMIT DROP AS
  SELECT
    mi.ingredient_id,
    SUM(oi.quantity * mi.quantity_required)::double precision AS required_quantity,
    string_agg(
      coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item') || ' x' || oi.quantity,
      ', '
      ORDER BY coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item')
    ) AS menu_summary
  FROM public.order_items oi
  LEFT JOIN public.menu m ON m.item_id = oi.menu_item_id
  JOIN public.menu_ingredients mi ON mi.menu_item_id = oi.menu_item_id
  WHERE oi.order_id = p_order_id
  GROUP BY mi.ingredient_id;

  IF NOT v_has_sale_transactions THEN
    IF EXISTS (
      SELECT 1
      FROM tmp_receive_ingredient_needs n
      JOIN public.inventory i ON i.ingredient_id = n.ingredient_id
      WHERE i.is_active = false
    ) THEN
      RAISE EXCEPTION 'ARCHIVED_INGREDIENT: one or more menu recipes use archived ingredients';
    END IF;

    FOR rec_stock IN
      SELECT
        i.ingredient_id,
        i.name,
        i.current_quantity,
        n.required_quantity,
        n.menu_summary
      FROM tmp_receive_ingredient_needs n
      JOIN public.inventory i ON i.ingredient_id = n.ingredient_id
      WHERE i.is_active = true
      ORDER BY i.ingredient_id
      FOR UPDATE OF i
    LOOP
      IF rec_stock.current_quantity < rec_stock.required_quantity THEN
        RAISE EXCEPTION 'INSUFFICIENT_STOCK: % required %, available %. Menu: %.',
          rec_stock.name,
          rec_stock.required_quantity,
          floor(rec_stock.current_quantity),
          rec_stock.menu_summary;
      END IF;
    END LOOP;

    FOR rec_stock IN
      SELECT
        i.ingredient_id,
        i.name,
        n.required_quantity
      FROM tmp_receive_ingredient_needs n
      JOIN public.inventory i ON i.ingredient_id = n.ingredient_id
      WHERE i.is_active = true
      ORDER BY i.ingredient_id
    LOOP
      UPDATE public.inventory i
      SET current_quantity = i.current_quantity - rec_stock.required_quantity
      WHERE i.ingredient_id = rec_stock.ingredient_id;

      INSERT INTO public.inventory_transactions (
        ingredient_id,
        quantity_change,
        transaction_type,
        reference_id,
        reason,
        cashier_id
      )
      VALUES (
        rec_stock.ingredient_id,
        -rec_stock.required_quantity,
        'sale',
        p_order_id,
        format('Received order %s ingredient deduction: %s', p_order_id, rec_stock.name),
        v_order.cashier_id
      );
    END LOOP;
  END IF;

  IF NOT v_has_payment THEN
    INSERT INTO public.payments (order_id, amount, payment_method)
    VALUES (p_order_id, v_order.total_amount, 'cash');
  END IF;

  UPDATE public.orders
  SET status = 'received'
  WHERE order_id = p_order_id
    AND status = 'pending';
END;
$$;

REVOKE ALL ON FUNCTION public.mark_order_received(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.mark_order_received(bigint) TO authenticated;

-- ============================================================================
-- 5) Cancel pending order
--    Useful for mistaken queue entries. It also repairs older pending orders that
--    already deducted inventory under the old confirm_pos_order function.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.cancel_pending_order(
  p_order_id bigint,
  p_reason text DEFAULT 'Cancelled pending order'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.orders%ROWTYPE;
  v_restored_transactions bigint := 0;
  v_deleted_payments bigint := 0;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'cancel_pending_order: not authorized (admin role required)';
  END IF;

  SELECT *
  INTO v_order
  FROM public.orders
  WHERE order_id = p_order_id
    AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'cancel_pending_order: order % not found or not pending', p_order_id;
  END IF;

  DROP TABLE IF EXISTS tmp_pending_inventory_reversals;

  CREATE TEMP TABLE tmp_pending_inventory_reversals ON COMMIT DROP AS
  SELECT
    it.ingredient_id,
    SUM(-it.quantity_change)::double precision AS quantity_restore
  FROM public.inventory_transactions it
  WHERE it.reference_id = p_order_id
    AND it.transaction_type = 'sale'
    AND it.quantity_change < 0
  GROUP BY it.ingredient_id;

  PERFORM 1
  FROM public.inventory i
  JOIN tmp_pending_inventory_reversals r ON r.ingredient_id = i.ingredient_id
  ORDER BY i.ingredient_id
  FOR UPDATE OF i;

  UPDATE public.inventory i
  SET current_quantity = i.current_quantity + r.quantity_restore
  FROM tmp_pending_inventory_reversals r
  WHERE r.ingredient_id = i.ingredient_id
    AND r.quantity_restore > 0;

  INSERT INTO public.inventory_transactions (
    ingredient_id,
    quantity_change,
    transaction_type,
    reference_id,
    reason,
    cashier_id
  )
  SELECT
    r.ingredient_id,
    r.quantity_restore,
    'void',
    p_order_id,
    format('Cancel pending order %s: restore sale deduction', p_order_id),
    v_order.cashier_id
  FROM tmp_pending_inventory_reversals r
  WHERE r.quantity_restore > 0;

  GET DIAGNOSTICS v_restored_transactions = ROW_COUNT;

  DELETE FROM public.payments
  WHERE order_id = p_order_id;

  GET DIAGNOSTICS v_deleted_payments = ROW_COUNT;

  UPDATE public.orders
  SET
    status = 'voided',
    voided_at = now(),
    void_reason = NULLIF(trim(coalesce(p_reason, '')), '')
  WHERE order_id = p_order_id
    AND status = 'pending';

  RETURN jsonb_build_object(
    'voided_order_id', p_order_id,
    'deleted_payments', v_deleted_payments,
    'restored_inventory_transactions', v_restored_transactions
  );
END;
$$;

REVOKE ALL ON FUNCTION public.cancel_pending_order(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cancel_pending_order(bigint, text) TO authenticated;

-- ============================================================================
-- 6) Inventory stock-in/stock-out RPCs
-- ============================================================================

CREATE OR REPLACE FUNCTION public.apply_inventory_stock_movement(
  p_ingredient_id bigint,
  p_quantity_change double precision,
  p_transaction_type text,
  p_reason text,
  p_reference_id bigint,
  p_cashier_id bigint,
  p_expense_amount double precision DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_inventory public.inventory%ROWTYPE;
  v_new_quantity double precision;
  v_transaction_id bigint;
  v_expense_id bigint;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: not authorized (admin role required)';
  END IF;

  IF p_ingredient_id IS NULL THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: p_ingredient_id is required';
  END IF;

  IF p_quantity_change IS NULL OR p_quantity_change = 0 THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: quantity change must not be zero';
  END IF;

  IF p_transaction_type NOT IN ('stock_in', 'stock_out') THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: invalid transaction type';
  END IF;

  IF p_expense_amount IS NULL THEN
    p_expense_amount := 0;
  END IF;

  IF p_expense_amount < 0 THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: expense amount must be zero or higher';
  END IF;

  IF p_expense_amount > 0 AND p_quantity_change < 0 THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: expense amount is only valid for stock in';
  END IF;

  SELECT *
  INTO v_inventory
  FROM public.inventory
  WHERE ingredient_id = p_ingredient_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: ingredient % not found', p_ingredient_id;
  END IF;

  IF v_inventory.is_active = false THEN
    RAISE EXCEPTION 'apply_inventory_stock_movement: ingredient % is archived', p_ingredient_id;
  END IF;

  v_new_quantity := v_inventory.current_quantity + p_quantity_change;

  IF v_new_quantity < 0 THEN
    RAISE EXCEPTION 'INSUFFICIENT_STOCK: % only has % %. Stock out cannot make inventory negative.',
      v_inventory.name,
      v_inventory.current_quantity,
      v_inventory.unit_of_measure;
  END IF;

  UPDATE public.inventory
  SET current_quantity = v_new_quantity
  WHERE ingredient_id = p_ingredient_id
  RETURNING * INTO v_inventory;

  INSERT INTO public.inventory_transactions (
    ingredient_id,
    quantity_change,
    transaction_type,
    reference_id,
    reason,
    cashier_id
  )
  VALUES (
    p_ingredient_id,
    p_quantity_change,
    p_transaction_type,
    p_reference_id,
    NULLIF(trim(coalesce(p_reason, '')), ''),
    p_cashier_id
  )
  RETURNING transaction_id INTO v_transaction_id;

  IF p_expense_amount > 0 THEN
    INSERT INTO public.expenses (
      expense_name,
      amount,
      category,
      cashier_id,
      notes
    )
    VALUES (
      format('Inventory stock in: %s', v_inventory.name),
      p_expense_amount,
      'Inventory',
      p_cashier_id,
      'Created from Inventory Stock In'
    )
    RETURNING expense_id INTO v_expense_id;
  END IF;

  RETURN jsonb_build_object(
    'inventory', to_jsonb(v_inventory),
    'transaction_id', v_transaction_id,
    'expense_id', v_expense_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.apply_inventory_stock_movement(bigint, double precision, text, text, bigint, bigint, double precision) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_inventory_stock_movement(bigint, double precision, text, text, bigint, bigint, double precision) TO authenticated;

CREATE OR REPLACE FUNCTION public.create_inventory_ingredient(
  p_name text,
  p_classification text,
  p_current_quantity double precision,
  p_unit_of_measure text,
  p_low_stock double precision,
  p_total_cost double precision,
  p_reference_id bigint,
  p_cashier_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_inventory public.inventory%ROWTYPE;
  v_transaction_id bigint;
  v_expense_id bigint;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'create_inventory_ingredient: not authorized (admin role required)';
  END IF;

  p_name := NULLIF(trim(coalesce(p_name, '')), '');
  p_classification := NULLIF(trim(coalesce(p_classification, '')), '');
  p_unit_of_measure := NULLIF(trim(coalesce(p_unit_of_measure, '')), '');

  IF p_name IS NULL THEN
    RAISE EXCEPTION 'create_inventory_ingredient: name is required';
  END IF;

  IF p_unit_of_measure IS NULL THEN
    RAISE EXCEPTION 'create_inventory_ingredient: unit of measure is required';
  END IF;

  IF p_current_quantity IS NULL OR p_current_quantity < 0 THEN
    RAISE EXCEPTION 'create_inventory_ingredient: current quantity must be zero or higher';
  END IF;

  IF p_low_stock IS NULL OR p_low_stock < 0 THEN
    RAISE EXCEPTION 'create_inventory_ingredient: low stock must be zero or higher';
  END IF;

  IF p_total_cost IS NULL THEN
    p_total_cost := 0;
  END IF;

  IF p_total_cost < 0 THEN
    RAISE EXCEPTION 'create_inventory_ingredient: total cost must be zero or higher';
  END IF;

  INSERT INTO public.inventory (
    name,
    classification,
    current_quantity,
    unit_of_measure,
    low_stock
  )
  VALUES (
    p_name,
    p_classification,
    p_current_quantity,
    p_unit_of_measure,
    p_low_stock
  )
  RETURNING * INTO v_inventory;

  IF p_current_quantity > 0 THEN
    INSERT INTO public.inventory_transactions (
      ingredient_id,
      quantity_change,
      transaction_type,
      reference_id,
      reason,
      cashier_id
    )
    VALUES (
      v_inventory.ingredient_id,
      p_current_quantity,
      'stock_in',
      p_reference_id,
      'Initial ingredient entry',
      p_cashier_id
    )
    RETURNING transaction_id INTO v_transaction_id;
  END IF;

  IF p_total_cost > 0 THEN
    INSERT INTO public.expenses (
      expense_name,
      amount,
      category,
      cashier_id,
      notes
    )
    VALUES (
      format('Inventory stock in: %s', p_name),
      p_total_cost,
      'Inventory',
      p_cashier_id,
      'Created from Inventory Stock In'
    )
    RETURNING expense_id INTO v_expense_id;
  END IF;

  RETURN jsonb_build_object(
    'inventory', to_jsonb(v_inventory),
    'transaction_id', v_transaction_id,
    'expense_id', v_expense_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_inventory_ingredient(text, text, double precision, text, double precision, double precision, bigint, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_inventory_ingredient(text, text, double precision, text, double precision, double precision, bigint, bigint) TO authenticated;

-- ============================================================================
-- 7) Queue, received, and sold-item report RPCs
-- ============================================================================

CREATE OR REPLACE FUNCTION public.list_pending_orders_with_items()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'list_pending_orders_with_items: not authorized (admin role required)';
  END IF;

  SELECT coalesce(
    jsonb_agg(
      jsonb_build_object(
        'order_id', o.order_id,
        'created_at', o.created_at,
        'cashier_id', o.cashier_id,
        'client_id', o.client_id,
        'total_amount', o.total_amount,
        'status', o.status,
        'guest_display_name', o.guest_display_name,
        'customer_display', coalesce(cl.full_name, o.guest_display_name, 'Guest'),
        'items', coalesce(li.items, '[]'::jsonb)
      )
      ORDER BY o.created_at ASC
    ),
    '[]'::jsonb
  )
  INTO v_result
  FROM public.orders o
  LEFT JOIN public.clients cl ON cl.client_id = o.client_id
  LEFT JOIN LATERAL (
    SELECT jsonb_agg(
      jsonb_build_object(
        'menu_item_id', oi.menu_item_id,
        'name', coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item'),
        'size_label', coalesce(oi.size_label_snapshot, m.size_label),
        'category', coalesce(oi.category_snapshot, m.category),
        'quantity', oi.quantity,
        'unit_price', oi.unit_price,
        'sub_total', oi.sub_total
      )
      ORDER BY oi.order_item_id
    ) AS items
    FROM public.order_items oi
    LEFT JOIN public.menu m ON m.item_id = oi.menu_item_id
    WHERE oi.order_id = o.order_id
  ) li ON true
  WHERE o.status = 'pending';

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.list_pending_orders_with_items() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_pending_orders_with_items() TO authenticated;

CREATE OR REPLACE FUNCTION public.list_received_orders_with_items()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'list_received_orders_with_items: not authorized (admin role required)';
  END IF;

  SELECT coalesce(
    jsonb_agg(
      jsonb_build_object(
        'order_id', o.order_id,
        'created_at', o.created_at,
        'cashier_id', o.cashier_id,
        'client_id', o.client_id,
        'total_amount', o.total_amount,
        'status', o.status,
        'guest_display_name', o.guest_display_name,
        'customer_display', coalesce(cl.full_name, o.guest_display_name, 'Guest'),
        'items', coalesce(li.items, '[]'::jsonb)
      )
      ORDER BY o.created_at DESC
    ),
    '[]'::jsonb
  )
  INTO v_result
  FROM public.orders o
  LEFT JOIN public.clients cl ON cl.client_id = o.client_id
  LEFT JOIN LATERAL (
    SELECT jsonb_agg(
      jsonb_build_object(
        'menu_item_id', oi.menu_item_id,
        'name', coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item'),
        'size_label', coalesce(oi.size_label_snapshot, m.size_label),
        'category', coalesce(oi.category_snapshot, m.category),
        'quantity', oi.quantity,
        'unit_price', oi.unit_price,
        'sub_total', oi.sub_total
      )
      ORDER BY oi.order_item_id
    ) AS items
    FROM public.order_items oi
    LEFT JOIN public.menu m ON m.item_id = oi.menu_item_id
    WHERE oi.order_id = o.order_id
  ) li ON true
  WHERE o.status = 'received';

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.list_received_orders_with_items() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_received_orders_with_items() TO authenticated;

CREATE OR REPLACE FUNCTION public.list_sold_items_report(
  p_start_at timestamp with time zone,
  p_end_at timestamp with time zone
)
RETURNS TABLE (
  menu_item_id bigint,
  item_name text,
  size_label text,
  category text,
  quantity_sold bigint,
  gross_sales double precision,
  order_count bigint,
  average_unit_price double precision,
  first_sold_at timestamp with time zone,
  last_sold_at timestamp with time zone
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'list_sold_items_report: not authorized (admin role required)';
  END IF;

  IF p_start_at IS NULL OR p_end_at IS NULL OR p_start_at >= p_end_at THEN
    RAISE EXCEPTION 'list_sold_items_report: invalid date range';
  END IF;

  RETURN QUERY
  SELECT
    oi.menu_item_id,
    coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item') AS item_name,
    coalesce(oi.size_label_snapshot, m.size_label) AS size_label,
    coalesce(oi.category_snapshot, m.category, 'Uncategorized') AS category,
    SUM(oi.quantity)::bigint AS quantity_sold,
    SUM(oi.sub_total)::double precision AS gross_sales,
    COUNT(DISTINCT o.order_id)::bigint AS order_count,
    (SUM(oi.sub_total) / NULLIF(SUM(oi.quantity), 0))::double precision AS average_unit_price,
    MIN(o.created_at) AS first_sold_at,
    MAX(o.created_at) AS last_sold_at
  FROM public.orders o
  JOIN public.order_items oi ON oi.order_id = o.order_id
  LEFT JOIN public.menu m ON m.item_id = oi.menu_item_id
  WHERE o.status = 'received'
    AND o.created_at >= p_start_at
    AND o.created_at < p_end_at
  GROUP BY
    oi.menu_item_id,
    coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item'),
    coalesce(oi.size_label_snapshot, m.size_label),
    coalesce(oi.category_snapshot, m.category, 'Uncategorized')
  ORDER BY
    SUM(oi.quantity) DESC,
    SUM(oi.sub_total) DESC,
    coalesce(oi.item_name_snapshot, m.name, 'Deleted Menu Item') ASC,
    coalesce(oi.size_label_snapshot, m.size_label) ASC;
END;
$$;

REVOKE ALL ON FUNCTION public.list_sold_items_report(timestamp with time zone, timestamp with time zone) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_sold_items_report(timestamp with time zone, timestamp with time zone) TO authenticated;

-- ============================================================================
-- 8) Void received receipts by date
-- ============================================================================

CREATE OR REPLACE FUNCTION public.void_received_orders_by_date(
  p_start_at timestamp with time zone,
  p_end_at timestamp with time zone,
  p_confirm_email text,
  p_confirm_action text,
  p_confirm_scope text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_voided_orders bigint := 0;
  v_restored_transactions bigint := 0;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'void_received_orders_by_date: not authorized (admin role required)';
  END IF;

  IF p_start_at IS NULL OR p_end_at IS NULL OR p_start_at >= p_end_at THEN
    RAISE EXCEPTION 'void_received_orders_by_date: invalid date range';
  END IF;

  IF lower(trim(coalesce(p_confirm_email, ''))) <> lower(coalesce(auth.jwt() ->> 'email', '')) THEN
    RAISE EXCEPTION 'void_received_orders_by_date: account email confirmation did not match';
  END IF;

  IF trim(coalesce(p_confirm_action, '')) <> 'VOID RECEIPTS' THEN
    RAISE EXCEPTION 'void_received_orders_by_date: first confirmation phrase did not match';
  END IF;

  IF trim(coalesce(p_confirm_scope, '')) <> 'VOID SELECTED DATE' THEN
    RAISE EXCEPTION 'void_received_orders_by_date: second confirmation phrase did not match';
  END IF;

  DROP TABLE IF EXISTS tmp_received_orders_to_void;
  DROP TABLE IF EXISTS tmp_inventory_reversals;

  CREATE TEMP TABLE tmp_received_orders_to_void ON COMMIT DROP AS
  SELECT o.order_id, o.cashier_id
  FROM public.orders o
  WHERE o.status = 'received'
    AND o.created_at >= p_start_at
    AND o.created_at < p_end_at;

  PERFORM 1
  FROM public.orders o
  JOIN tmp_received_orders_to_void d ON d.order_id = o.order_id
  ORDER BY o.order_id
  FOR UPDATE OF o;

  CREATE TEMP TABLE tmp_inventory_reversals ON COMMIT DROP AS
  SELECT
    it.reference_id AS order_id,
    o.cashier_id,
    it.ingredient_id,
    SUM(-it.quantity_change)::double precision AS quantity_restore
  FROM public.inventory_transactions it
  JOIN tmp_received_orders_to_void o ON o.order_id = it.reference_id
  WHERE it.transaction_type = 'sale'
    AND it.quantity_change < 0
  GROUP BY it.reference_id, o.cashier_id, it.ingredient_id;

  PERFORM 1
  FROM public.inventory i
  JOIN tmp_inventory_reversals r ON r.ingredient_id = i.ingredient_id
  ORDER BY i.ingredient_id
  FOR UPDATE OF i;

  UPDATE public.inventory i
  SET current_quantity = i.current_quantity + r.quantity_restore
  FROM (
    SELECT ingredient_id, SUM(quantity_restore)::double precision AS quantity_restore
    FROM tmp_inventory_reversals
    GROUP BY ingredient_id
  ) r
  WHERE r.ingredient_id = i.ingredient_id;

  INSERT INTO public.inventory_transactions (
    ingredient_id,
    quantity_change,
    transaction_type,
    reference_id,
    reason,
    cashier_id
  )
  SELECT
    r.ingredient_id,
    r.quantity_restore,
    'void',
    r.order_id,
    format('Void received order %s: restore sale deduction', r.order_id),
    r.cashier_id
  FROM tmp_inventory_reversals r
  WHERE r.quantity_restore > 0;

  GET DIAGNOSTICS v_restored_transactions = ROW_COUNT;

  UPDATE public.orders o
  SET
    status = 'voided',
    voided_at = now(),
    void_reason = 'Voided from received receipt history cleanup'
  FROM tmp_received_orders_to_void d
  WHERE d.order_id = o.order_id
    AND o.status = 'received';

  GET DIAGNOSTICS v_voided_orders = ROW_COUNT;

  RETURN jsonb_build_object(
    'deleted_payments', 0,
    'deleted_order_items', 0,
    'deleted_orders', 0,
    'voided_orders', v_voided_orders,
    'restored_inventory_transactions', v_restored_transactions
  );
END;
$$;

REVOKE ALL ON FUNCTION public.void_received_orders_by_date(timestamp with time zone, timestamp with time zone, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.void_received_orders_by_date(timestamp with time zone, timestamp with time zone, text, text, text) TO authenticated;

-- Backward-compatible website RPC name.
CREATE OR REPLACE FUNCTION public.delete_received_orders_by_date(
  p_start_at timestamp with time zone,
  p_end_at timestamp with time zone,
  p_confirm_email text,
  p_confirm_action text,
  p_confirm_scope text
)
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.void_received_orders_by_date(
    p_start_at,
    p_end_at,
    p_confirm_email,
    p_confirm_action,
    p_confirm_scope
  );
$$;

REVOKE ALL ON FUNCTION public.delete_received_orders_by_date(timestamp with time zone, timestamp with time zone, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_received_orders_by_date(timestamp with time zone, timestamp with time zone, text, text, text) TO authenticated;

-- ============================================================================
-- 9) Safer revenue reset
--    Does not delete orders/order_items/payments. It voids all active orders so
--    reports reset, restores sale inventory deductions, and clears expenses.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.reset_revenue_data(
  p_confirm_email text,
  p_confirm_action text,
  p_confirm_scope text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_auth_email text := coalesce(auth.jwt() ->> 'email', '');
  v_voided_orders bigint := 0;
  v_deleted_expenses bigint := 0;
  v_restored_transactions bigint := 0;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'reset_revenue_data: not authorized (admin role required)';
  END IF;

  IF lower(trim(coalesce(p_confirm_email, ''))) <> lower(trim(v_auth_email)) THEN
    RAISE EXCEPTION 'reset_revenue_data: account email confirmation did not match';
  END IF;

  IF trim(coalesce(p_confirm_action, '')) <> 'RESET REVENUE' THEN
    RAISE EXCEPTION 'reset_revenue_data: first confirmation phrase did not match';
  END IF;

  IF trim(coalesce(p_confirm_scope, '')) <> 'DELETE ORDERS AND EXPENSES' THEN
    RAISE EXCEPTION 'reset_revenue_data: second confirmation phrase did not match';
  END IF;

  DROP TABLE IF EXISTS tmp_reset_orders_to_void;
  DROP TABLE IF EXISTS tmp_reset_inventory_reversals;

  CREATE TEMP TABLE tmp_reset_orders_to_void ON COMMIT DROP AS
  SELECT o.order_id, o.cashier_id
  FROM public.orders o
  WHERE o.status IN ('pending', 'received');

  PERFORM 1
  FROM public.orders o
  JOIN tmp_reset_orders_to_void d ON d.order_id = o.order_id
  ORDER BY o.order_id
  FOR UPDATE OF o;

  CREATE TEMP TABLE tmp_reset_inventory_reversals ON COMMIT DROP AS
  SELECT
    it.reference_id AS order_id,
    o.cashier_id,
    it.ingredient_id,
    SUM(-it.quantity_change)::double precision AS quantity_restore
  FROM public.inventory_transactions it
  JOIN tmp_reset_orders_to_void o ON o.order_id = it.reference_id
  WHERE it.transaction_type = 'sale'
    AND it.quantity_change < 0
  GROUP BY it.reference_id, o.cashier_id, it.ingredient_id;

  PERFORM 1
  FROM public.inventory i
  JOIN tmp_reset_inventory_reversals r ON r.ingredient_id = i.ingredient_id
  ORDER BY i.ingredient_id
  FOR UPDATE OF i;

  UPDATE public.inventory i
  SET current_quantity = i.current_quantity + r.quantity_restore
  FROM (
    SELECT ingredient_id, SUM(quantity_restore)::double precision AS quantity_restore
    FROM tmp_reset_inventory_reversals
    GROUP BY ingredient_id
  ) r
  WHERE r.ingredient_id = i.ingredient_id;

  INSERT INTO public.inventory_transactions (
    ingredient_id,
    quantity_change,
    transaction_type,
    reference_id,
    reason,
    cashier_id
  )
  SELECT
    r.ingredient_id,
    r.quantity_restore,
    'void',
    r.order_id,
    format('Revenue reset void order %s: restore sale deduction', r.order_id),
    r.cashier_id
  FROM tmp_reset_inventory_reversals r
  WHERE r.quantity_restore > 0;

  GET DIAGNOSTICS v_restored_transactions = ROW_COUNT;

  UPDATE public.orders o
  SET
    status = 'voided',
    voided_at = now(),
    void_reason = 'Voided by revenue reset'
  FROM tmp_reset_orders_to_void d
  WHERE d.order_id = o.order_id
    AND o.status IN ('pending', 'received');

  GET DIAGNOSTICS v_voided_orders = ROW_COUNT;

  DELETE FROM public.expenses WHERE true;
  GET DIAGNOSTICS v_deleted_expenses = ROW_COUNT;

  RETURN jsonb_build_object(
    'deleted_payments', 0,
    'deleted_order_items', 0,
    'deleted_orders', 0,
    'deleted_expenses', v_deleted_expenses,
    'voided_orders', v_voided_orders,
    'restored_inventory_transactions', v_restored_transactions
  );
END;
$$;

REVOKE ALL ON FUNCTION public.reset_revenue_data(text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_revenue_data(text, text, text) TO authenticated;

-- ============================================================================
-- 10) Friendly activity logs
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.activity_logs (
  activity_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_id uuid,
  actor_email text,
  area text NOT NULL DEFAULT 'General',
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  entity_name text,
  description text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS activity_logs_created_at_idx
  ON public.activity_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS activity_logs_area_action_idx
  ON public.activity_logs (area, action, created_at DESC);

CREATE OR REPLACE FUNCTION public.activity_log_number(p_value jsonb)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_value IS NULL OR p_value = 'null'::jsonb THEN '0'
    ELSE to_char((p_value #>> '{}')::numeric, 'FM999999999999990.##')
  END;
$$;

CREATE OR REPLACE FUNCTION public.activity_log_money(p_value jsonb)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT 'PHP ' || public.activity_log_number(p_value);
$$;

CREATE OR REPLACE FUNCTION public.activity_log_first_changed_field(p_old jsonb, p_new jsonb, p_fields text[])
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_field text;
BEGIN
  FOREACH v_field IN ARRAY p_fields
  LOOP
    IF (p_old -> v_field) IS DISTINCT FROM (p_new -> v_field) THEN
      RETURN v_field;
    END IF;
  END LOOP;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.activity_log_table_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old jsonb := NULL;
  v_new jsonb := NULL;
  v_row jsonb;
  v_area text := 'General';
  v_action text := lower(TG_OP);
  v_entity_type text := TG_TABLE_NAME;
  v_entity_id text;
  v_entity_name text;
  v_description text;
  v_metadata jsonb;
  v_changed_field text;
  v_menu_name text;
  v_ingredient_name text;
  v_quantity text;
  v_unit text;
BEGIN
  IF TG_TABLE_NAME IN ('audit_logs', 'activity_logs') THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    v_new := to_jsonb(NEW);
    v_row := v_new;
  ELSIF TG_OP = 'UPDATE' THEN
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    v_row := v_new;

    IF v_old = v_new THEN
      RETURN NEW;
    END IF;
  ELSE
    v_old := to_jsonb(OLD);
    v_row := v_old;
  END IF;

  v_metadata := jsonb_build_object(
    'table_name', TG_TABLE_NAME,
    'operation', TG_OP,
    'old_data', v_old,
    'new_data', v_new
  );

  CASE TG_TABLE_NAME
    WHEN 'inventory' THEN
      v_area := 'Inventory';
      v_entity_type := 'Ingredient';
      v_entity_id := v_row ->> 'ingredient_id';
      v_entity_name := coalesce(v_row ->> 'name', 'Ingredient #' || coalesce(v_entity_id, '?'));

      IF TG_OP = 'INSERT' THEN
        v_action := 'create';
        v_description := format(
          'Added ingredient %s with %s %s on hand.',
          v_entity_name,
          public.activity_log_number(v_new -> 'current_quantity'),
          coalesce(v_new ->> 'unit_of_measure', 'unit')
        );
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'delete';
        v_description := format('Deleted ingredient %s.', v_entity_name);
      ELSE
        IF (v_old -> 'current_quantity') IS DISTINCT FROM (v_new -> 'current_quantity') THEN
          v_action := 'stock_update';
          v_description := format(
            '%s stock changed from %s %s to %s %s.',
            v_entity_name,
            public.activity_log_number(v_old -> 'current_quantity'),
            coalesce(v_old ->> 'unit_of_measure', 'unit'),
            public.activity_log_number(v_new -> 'current_quantity'),
            coalesce(v_new ->> 'unit_of_measure', 'unit')
          );
        ELSIF (v_old -> 'is_active') IS DISTINCT FROM (v_new -> 'is_active') THEN
          v_action := CASE WHEN coalesce((v_new ->> 'is_active')::boolean, true) THEN 'restore' ELSE 'archive' END;
          v_description := CASE
            WHEN coalesce((v_new ->> 'is_active')::boolean, true) THEN format('Restored ingredient %s.', v_entity_name)
            ELSE format('Archived ingredient %s.', v_entity_name)
          END;
        ELSE
          v_changed_field := public.activity_log_first_changed_field(
            v_old,
            v_new,
            ARRAY['name', 'classification', 'unit_of_measure', 'low_stock']
          );
          v_action := 'update';
          v_description := CASE v_changed_field
            WHEN 'name' THEN format('Renamed ingredient from %s to %s.', v_old ->> 'name', v_new ->> 'name')
            WHEN 'classification' THEN format('Changed %s type from %s to %s.', v_entity_name, coalesce(v_old ->> 'classification', 'blank'), coalesce(v_new ->> 'classification', 'blank'))
            WHEN 'unit_of_measure' THEN format('Changed %s unit from %s to %s.', v_entity_name, coalesce(v_old ->> 'unit_of_measure', 'blank'), coalesce(v_new ->> 'unit_of_measure', 'blank'))
            WHEN 'low_stock' THEN format('Changed %s low-stock alert from %s to %s.', v_entity_name, public.activity_log_number(v_old -> 'low_stock'), public.activity_log_number(v_new -> 'low_stock'))
            ELSE format('Updated ingredient %s.', v_entity_name)
          END;
        END IF;
      END IF;

    WHEN 'inventory_transactions' THEN
      v_area := 'Inventory';
      v_entity_type := 'Stock Movement';
      v_entity_id := v_row ->> 'transaction_id';
      v_action := coalesce(v_row ->> 'transaction_type', lower(TG_OP));
      v_quantity := public.activity_log_number(v_row -> 'quantity_change');

      SELECT i.name, i.unit_of_measure
      INTO v_ingredient_name, v_unit
      FROM public.inventory i
      WHERE i.ingredient_id = (v_row ->> 'ingredient_id')::bigint;

      v_entity_name := coalesce(v_ingredient_name, 'Ingredient #' || coalesce(v_row ->> 'ingredient_id', '?'));

      IF TG_OP = 'INSERT' THEN
        IF v_action = 'sale' THEN
          v_description := format('Deducted %s %s from %s for order #%s.', v_quantity, coalesce(v_unit, 'unit'), v_entity_name, coalesce(v_row ->> 'reference_id', '?'));
        ELSIF v_action = 'void' THEN
          v_description := format('Restored %s %s to %s for voided order #%s.', v_quantity, coalesce(v_unit, 'unit'), v_entity_name, coalesce(v_row ->> 'reference_id', '?'));
        ELSIF v_action = 'stock_in' THEN
          v_description := format('Added %s %s to %s.', v_quantity, coalesce(v_unit, 'unit'), v_entity_name);
        ELSIF v_action = 'stock_out' THEN
          v_description := format('Removed %s %s from %s.', replace(v_quantity, '-', ''), coalesce(v_unit, 'unit'), v_entity_name);
        ELSE
          v_description := format('Recorded %s movement for %s: %s %s.', v_action, v_entity_name, v_quantity, coalesce(v_unit, 'unit'));
        END IF;

        IF nullif(trim(coalesce(v_row ->> 'reason', '')), '') IS NOT NULL THEN
          v_description := v_description || ' Reason: ' || (v_row ->> 'reason');
        END IF;
      ELSE
        v_description := format('%s stock movement for %s.', initcap(lower(TG_OP)), v_entity_name);
      END IF;

    WHEN 'menu' THEN
      v_area := 'Menu';
      v_entity_type := 'Menu Item';
      v_entity_id := v_row ->> 'item_id';
      v_entity_name := coalesce(v_row ->> 'name', 'Menu item #' || coalesce(v_entity_id, '?'));

      IF TG_OP = 'INSERT' THEN
        v_action := 'create';
        v_description := format('Added menu item %s for %s.', v_entity_name, public.activity_log_money(v_new -> 'price'));
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'delete';
        v_description := format('Deleted menu item %s.', v_entity_name);
      ELSE
        IF (v_old -> 'price') IS DISTINCT FROM (v_new -> 'price') THEN
          v_action := 'price_update';
          v_description := format('%s price changed from %s to %s.', v_entity_name, public.activity_log_money(v_old -> 'price'), public.activity_log_money(v_new -> 'price'));
        ELSIF (v_old -> 'availability_status') IS DISTINCT FROM (v_new -> 'availability_status') THEN
          v_action := 'availability_update';
          v_description := format('%s availability changed from %s to %s.', v_entity_name, coalesce(v_old ->> 'availability_status', 'blank'), coalesce(v_new ->> 'availability_status', 'blank'));
        ELSE
          v_changed_field := public.activity_log_first_changed_field(
            v_old,
            v_new,
            ARRAY['name', 'size_label', 'category', 'description', 'image_url']
          );
          v_action := 'update';
          v_description := CASE v_changed_field
            WHEN 'name' THEN format('Renamed menu item from %s to %s.', v_old ->> 'name', v_new ->> 'name')
            WHEN 'size_label' THEN format('Changed %s size from %s to %s.', v_entity_name, coalesce(v_old ->> 'size_label', 'blank'), coalesce(v_new ->> 'size_label', 'blank'))
            WHEN 'category' THEN format('Moved %s from %s to %s.', v_entity_name, coalesce(v_old ->> 'category', 'blank'), coalesce(v_new ->> 'category', 'blank'))
            WHEN 'image_url' THEN format('Updated photo for %s.', v_entity_name)
            ELSE format('Updated menu item %s.', v_entity_name)
          END;
        END IF;
      END IF;

    WHEN 'menu_ingredients' THEN
      v_area := 'Menu';
      v_entity_type := 'Recipe Ingredient';
      v_entity_id := v_row ->> 'menu_ingredient_id';

      SELECT m.name
      INTO v_menu_name
      FROM public.menu m
      WHERE m.item_id = (v_row ->> 'menu_item_id')::bigint;

      SELECT i.name, i.unit_of_measure
      INTO v_ingredient_name, v_unit
      FROM public.inventory i
      WHERE i.ingredient_id = (v_row ->> 'ingredient_id')::bigint;

      v_entity_name := coalesce(v_menu_name, 'Menu item #' || coalesce(v_row ->> 'menu_item_id', '?'));

      IF TG_OP = 'INSERT' THEN
        v_action := 'recipe_add';
        v_description := format(
          'Linked %s to %s recipe: %s %s per item.',
          coalesce(v_ingredient_name, 'ingredient #' || coalesce(v_row ->> 'ingredient_id', '?')),
          v_entity_name,
          public.activity_log_number(v_new -> 'quantity_required'),
          coalesce(v_new ->> 'unit_of_measure', v_unit, 'unit')
        );
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'recipe_remove';
        v_description := format('Removed %s from %s recipe.', coalesce(v_ingredient_name, 'ingredient'), v_entity_name);
      ELSE
        v_action := 'recipe_update';
        v_description := format(
          'Updated %s recipe ingredient %s from %s %s to %s %s.',
          v_entity_name,
          coalesce(v_ingredient_name, 'ingredient'),
          public.activity_log_number(v_old -> 'quantity_required'),
          coalesce(v_old ->> 'unit_of_measure', v_unit, 'unit'),
          public.activity_log_number(v_new -> 'quantity_required'),
          coalesce(v_new ->> 'unit_of_measure', v_unit, 'unit')
        );
      END IF;

    WHEN 'orders' THEN
      v_area := 'Revenue';
      v_entity_type := 'Order';
      v_entity_id := v_row ->> 'order_id';
      v_entity_name := 'Order #' || coalesce(v_entity_id, '?');

      IF TG_OP = 'INSERT' THEN
        v_action := 'order_create';
        v_description := format('Created pending order #%s for %s.', coalesce(v_entity_id, '?'), public.activity_log_money(v_new -> 'total_amount'));
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'order_delete';
        v_description := format('Deleted order #%s.', coalesce(v_entity_id, '?'));
      ELSIF (v_old -> 'status') IS DISTINCT FROM (v_new -> 'status') THEN
        v_action := CASE v_new ->> 'status'
          WHEN 'received' THEN 'order_received'
          WHEN 'voided' THEN 'order_voided'
          ELSE 'order_status_update'
        END;
        v_description := CASE v_new ->> 'status'
          WHEN 'received' THEN format('Marked order #%s as received.', coalesce(v_entity_id, '?'))
          WHEN 'voided' THEN format('Voided order #%s. Reason: %s', coalesce(v_entity_id, '?'), coalesce(nullif(v_new ->> 'void_reason', ''), 'No reason provided'))
          ELSE format('Changed order #%s status from %s to %s.', coalesce(v_entity_id, '?'), coalesce(v_old ->> 'status', 'blank'), coalesce(v_new ->> 'status', 'blank'))
        END;
      ELSE
        v_action := 'order_update';
        v_description := format('Updated order #%s.', coalesce(v_entity_id, '?'));
      END IF;

    WHEN 'payments' THEN
      v_area := 'Revenue';
      v_entity_type := 'Payment';
      v_entity_id := v_row ->> 'payment_id';
      v_entity_name := 'Payment #' || coalesce(v_entity_id, '?');

      IF TG_OP = 'INSERT' THEN
        v_action := 'payment_recorded';
        v_description := format(
          'Recorded %s payment of %s for order #%s.',
          coalesce(v_new ->> 'payment_method', 'payment'),
          public.activity_log_money(v_new -> 'amount'),
          coalesce(v_new ->> 'order_id', '?')
        );
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'payment_delete';
        v_description := format('Deleted payment #%s for order #%s.', coalesce(v_entity_id, '?'), coalesce(v_old ->> 'order_id', '?'));
      ELSE
        v_action := 'payment_update';
        v_description := format('Updated payment #%s.', coalesce(v_entity_id, '?'));
      END IF;

    WHEN 'expenses' THEN
      v_area := 'Revenue';
      v_entity_type := 'Expense';
      v_entity_id := v_row ->> 'expense_id';
      v_entity_name := coalesce(v_row ->> 'expense_name', 'Expense #' || coalesce(v_entity_id, '?'));

      IF TG_OP = 'INSERT' THEN
        v_action := 'expense_create';
        v_description := format('Recorded expense %s for %s.', v_entity_name, public.activity_log_money(v_new -> 'amount'));
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'expense_delete';
        v_description := format('Deleted expense %s.', v_entity_name);
      ELSIF (v_old -> 'amount') IS DISTINCT FROM (v_new -> 'amount') THEN
        v_action := 'expense_update';
        v_description := format('%s amount changed from %s to %s.', v_entity_name, public.activity_log_money(v_old -> 'amount'), public.activity_log_money(v_new -> 'amount'));
      ELSE
        v_action := 'expense_update';
        v_description := format('Updated expense %s.', v_entity_name);
      END IF;

    WHEN 'order_items' THEN
      v_area := 'Revenue';
      v_entity_type := 'Order Item';
      v_entity_id := v_row ->> 'order_item_id';
      v_entity_name := coalesce(v_row ->> 'item_name_snapshot', 'Menu item #' || coalesce(v_row ->> 'menu_item_id', '?'));

      IF TG_OP = 'INSERT' THEN
        v_action := 'order_item_add';
        v_description := format(
          'Added %s x%s to order #%s.',
          v_entity_name,
          coalesce(v_new ->> 'quantity', '?'),
          coalesce(v_new ->> 'order_id', '?')
        );
      ELSIF TG_OP = 'DELETE' THEN
        v_action := 'order_item_delete';
        v_description := format('Removed %s from order #%s.', v_entity_name, coalesce(v_old ->> 'order_id', '?'));
      ELSE
        v_action := 'order_item_update';
        v_description := format('Updated %s in order #%s.', v_entity_name, coalesce(v_new ->> 'order_id', '?'));
      END IF;

    ELSE
      v_area := 'General';
      v_action := lower(TG_OP);
      v_entity_type := TG_TABLE_NAME;
      v_description := format('%s on %s.', initcap(lower(TG_OP)), TG_TABLE_NAME);
  END CASE;

  INSERT INTO public.activity_logs (
    actor_id,
    actor_email,
    area,
    action,
    entity_type,
    entity_id,
    entity_name,
    description,
    metadata
  )
  VALUES (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', 'system'),
    v_area,
    v_action,
    v_entity_type,
    v_entity_id,
    v_entity_name,
    v_description,
    v_metadata
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT *
    FROM (VALUES
      ('inventory'),
      ('inventory_transactions'),
      ('menu'),
      ('menu_ingredients'),
      ('orders'),
      ('order_items'),
      ('payments'),
      ('expenses')
    ) AS tracked(table_name)
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS activity_%I_changes ON public.%I', rec.table_name, rec.table_name);
    EXECUTE format(
      'CREATE TRIGGER activity_%I_changes AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.activity_log_table_change()',
      rec.table_name,
      rec.table_name
    );
  END LOOP;
END $$;

-- ============================================================================
-- 11) Audit logs
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.audit_logs (
  log_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_id uuid,
  actor_email text,
  action text NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
  schema_name text NOT NULL DEFAULT 'public',
  table_name text NOT NULL,
  record_pk jsonb NOT NULL DEFAULT '{}'::jsonb,
  summary text,
  old_data jsonb,
  new_data jsonb
);

CREATE INDEX IF NOT EXISTS audit_logs_created_at_idx
  ON public.audit_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_table_action_idx
  ON public.audit_logs (table_name, action, created_at DESC);

CREATE OR REPLACE FUNCTION public.audit_record_pk(p_table_name text, p_row jsonb)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  CASE p_table_name
    WHEN 'inventory' THEN
      RETURN jsonb_build_object('ingredient_id', p_row -> 'ingredient_id');
    WHEN 'inventory_transactions' THEN
      RETURN jsonb_build_object('transaction_id', p_row -> 'transaction_id');
    WHEN 'menu' THEN
      RETURN jsonb_build_object('item_id', p_row -> 'item_id');
    WHEN 'menu_ingredients' THEN
      RETURN jsonb_build_object('menu_ingredient_id', p_row -> 'menu_ingredient_id');
    WHEN 'orders' THEN
      RETURN jsonb_build_object('order_id', p_row -> 'order_id');
    WHEN 'order_items' THEN
      RETURN jsonb_build_object('order_item_id', p_row -> 'order_item_id');
    WHEN 'payments' THEN
      RETURN jsonb_build_object('payment_id', p_row -> 'payment_id');
    WHEN 'expenses' THEN
      RETURN jsonb_build_object('expense_id', p_row -> 'expense_id');
    ELSE
      RETURN '{}'::jsonb;
  END CASE;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_log_table_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old jsonb;
  v_new jsonb;
  v_pk jsonb;
  v_summary text;
BEGIN
  IF TG_TABLE_NAME = 'audit_logs' THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    v_new := to_jsonb(NEW);
    v_pk := public.audit_record_pk(TG_TABLE_NAME, v_new);
    v_summary := format('%s inserted', TG_TABLE_NAME);
  ELSIF TG_OP = 'UPDATE' THEN
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    v_pk := public.audit_record_pk(TG_TABLE_NAME, v_new);
    v_summary := format('%s updated', TG_TABLE_NAME);
  ELSE
    v_old := to_jsonb(OLD);
    v_pk := public.audit_record_pk(TG_TABLE_NAME, v_old);
    v_summary := format('%s deleted', TG_TABLE_NAME);
  END IF;

  INSERT INTO public.audit_logs (
    actor_id,
    actor_email,
    action,
    schema_name,
    table_name,
    record_pk,
    summary,
    old_data,
    new_data
  )
  VALUES (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', 'system'),
    TG_OP,
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    v_pk,
    v_summary,
    v_old,
    v_new
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT *
    FROM (VALUES
      ('inventory'),
      ('inventory_transactions'),
      ('menu'),
      ('menu_ingredients'),
      ('orders'),
      ('order_items'),
      ('payments'),
      ('expenses')
    ) AS tracked(table_name)
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_%I_changes ON public.%I', rec.table_name, rec.table_name);
    EXECUTE format(
      'CREATE TRIGGER audit_%I_changes AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.audit_log_table_change()',
      rec.table_name,
      rec.table_name
    );
  END LOOP;
END $$;

-- ============================================================================
-- 11) RLS read lockdown
-- ============================================================================

ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "inventory_select_authenticated" ON public.inventory;
DROP POLICY IF EXISTS "inventory_select_admin_only" ON public.inventory;
CREATE POLICY "inventory_select_admin_only"
ON public.inventory
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "inventory_tx_read_authenticated" ON public.inventory_transactions;
DROP POLICY IF EXISTS "inventory_tx_read_admin_only" ON public.inventory_transactions;
CREATE POLICY "inventory_tx_read_admin_only"
ON public.inventory_transactions
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "menu_select_authenticated" ON public.menu;
DROP POLICY IF EXISTS "menu_select_admin_only" ON public.menu;
CREATE POLICY "menu_select_admin_only"
ON public.menu
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "menu_ingredients_select_authenticated" ON public.menu_ingredients;
DROP POLICY IF EXISTS "menu_ingredients_select_admin_only" ON public.menu_ingredients;
CREATE POLICY "menu_ingredients_select_admin_only"
ON public.menu_ingredients
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "expenses_select_authenticated" ON public.expenses;
DROP POLICY IF EXISTS "expenses_select_admin_only" ON public.expenses;
CREATE POLICY "expenses_select_admin_only"
ON public.expenses
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "activity_logs_select_admin_only" ON public.activity_logs;
CREATE POLICY "activity_logs_select_admin_only"
ON public.activity_logs
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "activity_logs_service_manage" ON public.activity_logs;
CREATE POLICY "activity_logs_service_manage"
ON public.activity_logs
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "audit_logs_select_admin_only" ON public.audit_logs;
CREATE POLICY "audit_logs_select_admin_only"
ON public.audit_logs
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "audit_logs_service_manage" ON public.audit_logs;
CREATE POLICY "audit_logs_service_manage"
ON public.audit_logs
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

REVOKE ALL ON public.audit_logs FROM PUBLIC;
REVOKE ALL ON public.activity_logs FROM PUBLIC;
GRANT SELECT ON public.activity_logs TO authenticated;
GRANT SELECT ON public.audit_logs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.activity_logs_activity_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.audit_logs_log_id_seq TO authenticated;
