-- Cozy Cafe POS: recipe-based menu ingredients for order confirmation.
-- Run after 20250515120000_pos_menu_orders_inventory.sql.
--
-- This replaces the older confirm_pos_order implementation that required
-- menu.inventory_ingredient_id. New menu items use rows in menu_ingredients
-- instead, so orders deduct every linked recipe ingredient.

CREATE TABLE IF NOT EXISTS public.menu_ingredients (
  menu_ingredient_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id bigint NOT NULL REFERENCES public.menu(item_id) ON DELETE CASCADE,
  ingredient_id bigint NOT NULL REFERENCES public.inventory(ingredient_id),
  quantity_required double precision NOT NULL CHECK (quantity_required > 0),
  unit_of_measure text
);

CREATE INDEX IF NOT EXISTS menu_ingredients_menu_item_id_idx
  ON public.menu_ingredients (menu_item_id);

CREATE INDEX IF NOT EXISTS menu_ingredients_ingredient_id_idx
  ON public.menu_ingredients (ingredient_id);

CREATE UNIQUE INDEX IF NOT EXISTS menu_ingredients_menu_item_ingredient_uq
  ON public.menu_ingredients (menu_item_id, ingredient_id);

ALTER TABLE public.menu_ingredients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "menu_ingredients_select_authenticated" ON public.menu_ingredients;
CREATE POLICY "menu_ingredients_select_authenticated"
ON public.menu_ingredients
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "menu_ingredients_modify_admin_only" ON public.menu_ingredients;
CREATE POLICY "menu_ingredients_modify_admin_only"
ON public.menu_ingredients
FOR ALL
TO authenticated
USING (public.is_admin_app_user())
WITH CHECK (public.is_admin_app_user());

CREATE OR REPLACE FUNCTION public.confirm_pos_order(
  p_cashier_id bigint,
  p_client_id bigint,
  p_guest_display_name text,
  p_lines jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order_id bigint;
  v_total double precision := 0;
  rec record;
BEGIN
  IF NOT public.is_admin_app_user() THEN
    RAISE EXCEPTION 'confirm_pos_order: not authorized (admin role required)';
  END IF;

  IF p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'confirm_pos_order: p_lines must be a non-empty JSON array';
  END IF;

  IF p_cashier_id IS NULL THEN
    RAISE EXCEPTION 'confirm_pos_order: p_cashier_id is required';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.cashier c WHERE c.cashier_id = p_cashier_id) THEN
    RAISE EXCEPTION 'confirm_pos_order: cashier_id % not found', p_cashier_id;
  END IF;

  IF p_client_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.clients cl WHERE cl.client_id = p_client_id) THEN
    RAISE EXCEPTION 'confirm_pos_order: client_id % not found', p_client_id;
  END IF;

  DROP TABLE IF EXISTS tmp_order_lines;
  DROP TABLE IF EXISTS tmp_ingredient_needs;

  CREATE TEMP TABLE tmp_order_lines ON COMMIT DROP AS
  WITH raw AS (
    SELECT
      (elem->>'menu_item_id')::bigint AS menu_item_id,
      (elem->>'quantity')::int AS quantity
    FROM jsonb_array_elements(p_lines) AS t(elem)
  ),
  cleaned AS (
    SELECT menu_item_id, quantity
    FROM raw
    WHERE menu_item_id IS NOT NULL AND quantity IS NOT NULL
  )
  SELECT menu_item_id, SUM(quantity)::int AS quantity
  FROM cleaned
  GROUP BY menu_item_id;

  IF NOT EXISTS (SELECT 1 FROM tmp_order_lines) THEN
    RAISE EXCEPTION 'confirm_pos_order: p_lines must include at least one valid menu item';
  END IF;

  IF EXISTS (SELECT 1 FROM tmp_order_lines WHERE quantity <= 0) THEN
    RAISE EXCEPTION 'confirm_pos_order: each quantity must be a positive integer';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM tmp_order_lines t
    LEFT JOIN public.menu m ON m.item_id = t.menu_item_id
    WHERE m.item_id IS NULL
  ) THEN
    RAISE EXCEPTION 'confirm_pos_order: unknown menu_item_id in cart';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM tmp_order_lines t
    JOIN public.menu m ON m.item_id = t.menu_item_id
    WHERE lower(coalesce(m.availability_status, '')) <> 'available'
  ) THEN
    RAISE EXCEPTION 'confirm_pos_order: one or more menu items are unavailable';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM tmp_order_lines t
    WHERE NOT EXISTS (
      SELECT 1
      FROM public.menu_ingredients mi
      WHERE mi.menu_item_id = t.menu_item_id
    )
  ) THEN
    RAISE EXCEPTION 'NO_RECIPE: one or more menu items do not have linked ingredients';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM tmp_order_lines t
    JOIN public.menu_ingredients mi ON mi.menu_item_id = t.menu_item_id
    JOIN public.inventory i ON i.ingredient_id = mi.ingredient_id
    WHERE i.is_active = false
  ) THEN
    RAISE EXCEPTION 'ARCHIVED_INGREDIENT: one or more menu recipes use archived ingredients';
  END IF;

  SELECT SUM(m.price * t.quantity)::double precision
  INTO v_total
  FROM tmp_order_lines t
  JOIN public.menu m ON m.item_id = t.menu_item_id;

  CREATE TEMP TABLE tmp_ingredient_needs ON COMMIT DROP AS
  SELECT
    mi.ingredient_id,
    SUM(t.quantity * mi.quantity_required)::double precision AS required_quantity,
    string_agg(m.name || ' x' || t.quantity, ', ' ORDER BY m.name) AS menu_summary
  FROM tmp_order_lines t
  JOIN public.menu m ON m.item_id = t.menu_item_id
  JOIN public.menu_ingredients mi ON mi.menu_item_id = t.menu_item_id
  GROUP BY mi.ingredient_id;

  FOR rec IN
    SELECT
      n.ingredient_id,
      n.required_quantity,
      n.menu_summary,
      i.name AS ingredient_name,
      i.current_quantity
    FROM tmp_ingredient_needs n
    JOIN public.inventory i ON i.ingredient_id = n.ingredient_id
    ORDER BY n.ingredient_id
    FOR UPDATE OF i
  LOOP
    IF rec.current_quantity < rec.required_quantity THEN
      RAISE EXCEPTION 'INSUFFICIENT_STOCK: % — needed %, available %. Used by: %.',
        rec.ingredient_name,
        rec.required_quantity,
        floor(rec.current_quantity),
        rec.menu_summary;
    END IF;
  END LOOP;

  INSERT INTO public.orders (cashier_id, client_id, total_amount, status, guest_display_name)
  VALUES (
    p_cashier_id,
    p_client_id,
    v_total,
    'pending',
    NULLIF(trim(coalesce(p_guest_display_name, '')), '')
  )
  RETURNING order_id INTO v_order_id;

  INSERT INTO public.order_items (order_id, menu_item_id, quantity, unit_price, sub_total)
  SELECT
    v_order_id,
    t.menu_item_id,
    t.quantity,
    m.price,
    m.price * t.quantity
  FROM tmp_order_lines t
  JOIN public.menu m ON m.item_id = t.menu_item_id
  ORDER BY t.menu_item_id;

  UPDATE public.inventory i
  SET current_quantity = i.current_quantity - n.required_quantity
  FROM tmp_ingredient_needs n
  WHERE i.ingredient_id = n.ingredient_id;

  INSERT INTO public.inventory_transactions (
    ingredient_id,
    quantity_change,
    transaction_type,
    reference_id,
    reason,
    cashier_id
  )
  SELECT
    n.ingredient_id,
    -n.required_quantity,
    'sale',
    v_order_id,
    format('POS order %s: %s', v_order_id, n.menu_summary),
    p_cashier_id
  FROM tmp_ingredient_needs n
  ORDER BY n.ingredient_id;

  RETURN v_order_id;
END;
$$;

REVOKE ALL ON FUNCTION public.confirm_pos_order(bigint, bigint, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.confirm_pos_order(bigint, bigint, text, jsonb) TO authenticated;
