-- Cozy Cafe Menu: manageable categories with optional parent categories.

CREATE TABLE IF NOT EXISTS public.menu_categories (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  parent_category_id bigint REFERENCES public.menu_categories(category_id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT menu_categories_name_parent_uq UNIQUE (name, parent_category_id)
);

CREATE INDEX IF NOT EXISTS menu_categories_parent_category_id_idx
  ON public.menu_categories (parent_category_id);

ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "menu_categories_select_authenticated" ON public.menu_categories;
CREATE POLICY "menu_categories_select_authenticated"
ON public.menu_categories
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "menu_categories_modify_admin_only" ON public.menu_categories;
CREATE POLICY "menu_categories_modify_admin_only"
ON public.menu_categories
FOR ALL
TO authenticated
USING (public.is_admin_app_user())
WITH CHECK (public.is_admin_app_user());

INSERT INTO public.menu_categories (name)
SELECT DISTINCT trim(v.name)
FROM (
  VALUES
    ('Rice Bowl Chicken Wings'),
    ('French Fries'),
    ('Waffles'),
    ('Soft Drinks'),
    ('Korean Rice Bowls'),
    ('Sandwiches'),
    ('Silog Bowls'),
    ('Others')
) AS v(name)
WHERE trim(v.name) <> ''
ON CONFLICT (name, parent_category_id) DO NOTHING;

INSERT INTO public.menu_categories (name)
SELECT DISTINCT trim(m.category)
FROM public.menu m
WHERE trim(coalesce(m.category, '')) <> ''
ON CONFLICT (name, parent_category_id) DO NOTHING;
