-- The Cozzy Cup Cafe POS: menu_ingredients table setup.
--
-- This migration now only creates the recipe bridge table and its indexes.
-- The current confirm_pos_order implementation lives in:
-- supabase/migrations/20250515161000_harden_orders_inventory_and_reports.sql

CREATE TABLE IF NOT EXISTS public.menu_ingredients (
  menu_ingredient_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id bigint NOT NULL REFERENCES public.menu(item_id) ON DELETE CASCADE,
  ingredient_id bigint NOT NULL REFERENCES public.inventory(ingredient_id),
  quantity_required double precision NOT NULL CHECK (quantity_required > 0),
  unit_of_measure text
);

ALTER TABLE public.menu_ingredients
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS menu_ingredients_menu_item_id_idx
  ON public.menu_ingredients (menu_item_id);

CREATE INDEX IF NOT EXISTS menu_ingredients_ingredient_id_idx
  ON public.menu_ingredients (ingredient_id);

CREATE UNIQUE INDEX IF NOT EXISTS menu_ingredients_menu_item_ingredient_uq
  ON public.menu_ingredients (menu_item_id, ingredient_id);

ALTER TABLE public.menu_ingredients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "menu_ingredients_select_authenticated" ON public.menu_ingredients;
DROP POLICY IF EXISTS "menu_ingredients_select_admin_only" ON public.menu_ingredients;
CREATE POLICY "menu_ingredients_select_admin_only"
ON public.menu_ingredients
FOR SELECT
TO authenticated
USING (public.is_admin_app_user());

DROP POLICY IF EXISTS "menu_ingredients_modify_admin_only" ON public.menu_ingredients;
CREATE POLICY "menu_ingredients_modify_admin_only"
ON public.menu_ingredients
FOR ALL
TO authenticated
USING (public.is_admin_app_user())
WITH CHECK (public.is_admin_app_user());

DO $$
BEGIN
  RAISE NOTICE '20250515143000 only prepares menu_ingredients. Run 20250515161000_harden_orders_inventory_and_reports.sql for the current order RPCs.';
END;
$$;
